on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [16.x, 17.x]

      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - run: npm cache clean --force
        - run: npm ci
        - run: npm run build
        - run: set CI
        - run: npm run test
        - run: npm run deploy
